server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testhtwo
    username: sa
    password: sa
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 120000

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.kevin.mpdel

