
spring:
  redis:
    host: localhost
    port: 6379
    password: myRedis
    lettuce:
      pool:
        max-active: 4 #default 8
        max-idle: 2 #default 8
        max-wait: 10000ms #default value is -1ms
        min-idle: 0 #default